### ISSUE TITLE
Export writes file over and over again

### ISSUE THREAD

**Issue by pscheid92** [jflesch/paperwork-backend#2] opened 2016-11-10 23:24 UTC
**Description:**

Exporting a document (pdf) or a single page (png) leads to a hanging paperwork.
The file is written and overwritten over and over again.

This can be detected by checking file size multiple time with bash or nautilus.
The size is growing, reset to 0 bytes and starts growing again.

I have to kill the paperwork process to stop it. Sometimes the kill leads to a well written file,
sometimes to binary garbage. Moreover, this is really bad for SSD lifespan.

If you need further information or want me to test a fixed branch version,
please be not afraid to ask.

**Environment:**

- Fedora 24 Linux
- Python 3.5.2
- Gnome 3.20.2
- Paperwork 1.0.1 (also occurs in 1.0.0) installed with pip3

**Reproduction:**

1. Opening a scanned or imported document (both tested).
2. Export the document to a given folder.
3. Start export with button.
4. Paperwork hangs.
5. Check size of output file with nautilus (or similar).

**Comment by jflesch** [comment] 2016-11-11 03:25
If you start Paperwork from a terminal and export the document, is there any message printed at each export ?

**Comment by jflesch** [comment] 2016-11-11 03:27
Also when you say "over and over", does it stop at some point, or does it loop forever ?

**Comment by pscheid92** [comment] 2016-11-11 11:14
I've waited for about 10 minutes and it didn't stop.
Seems like an endless loop to me.

I run Paperwork from terminal and captured the output.
Here are the pastebin.com links:

- [Normal Logging](http://pastebin.com/q6DZWpFj)
- [DEBUG Logging](http://pastebin.com/8u3Rmk2C)

In a terminal the following lines are printed out.
They always appear, when the file is written again.

```
INFO   paperwork_backend.img.doc      Adding text to PDF page 20161110_2352_51 p1 ...
INFO   paperwork_backend.img.doc      Adding image to PDF page 20161110_2352_51 p1 ...
INFO   paperwork_backend.img.doc      Page 20161110_2352_51 p1 ready
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 1898, in _do
    self.main_win.set_mouse_cursor("Normal")
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2714, in set_mouse_cursor
    assert(self.__busy_mouse_counter >= 0)
AssertionError
INFO   paperwork_backend.img.doc      Adding text to PDF page 20161110_2352_51 p1 ...
INFO   paperwork_backend.img.doc      Adding image to PDF page 20161110_2352_51 p1 ...
INFO   paperwork_backend.img.doc      Page 20161110_2352_51 p1 ready
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 1898, in _do
    self.main_win.set_mouse_cursor("Normal")
  File "/usr/lib/python3.5/site-packages/paperwork/frontend/mainwindow/__init__.py", line 2714, in set_mouse_cursor
    assert(self.__busy_mouse_counter >= 0)
AssertionError
```

**Comment by jflesch** [comment] 2016-11-11 13:47
Ok, definitively a bug I don't have here (Debian sid) (.. and I wouldn't be surprised if it is due to another weird behavior of Gtk with the export dialog ...).
I guess I will have to install a Fedora VM

**Comment by jflesch** [comment] 2016-11-11 15:19
BTW, I forgot to ask : At which point is it looping exactly ? When it is trying to display the preview of the export, of when it is actually exporting ? (your logs suggest when it is trying to display the preview if I'm not mistaken)

**Comment by pscheid92** [comment] 2016-11-11 20:59
The preview works fine. The loop occurs while exporting.
The file is fully written on the disk. After that it is written again. And again, and again.
Always overwriting the already created file.

**Comment by jflesch** [comment] 2016-11-12 17:59
Reproduced on Fedora 24 in a VM.

**Comment by jflesch** [comment] 2016-11-12 18:17
Grmpf, the version of Gtk / Gobject on Fedora 24 seem *really* buggy. Even my Gvim is full of visual artefacts.

Anyway, here, it seems that when I call GLib.idle_add(callback), for some unknown reason, it calls the callback in loop forever ... exporting each time the document ...

**Comment by jflesch** [comment] 2016-11-12 18:18
I doubt I will be able to make a small test program showing the same problem (I fear a stack corruption far before the export itself). So for now, I will just see if I can workaround it.

**Comment by jflesch** [comment] 2016-11-12 19:39
Fixed : https://github.com/jflesch/paperwork/commit/4d30477f9ab6980010682a32cfee16bf3014b970
It was actually my fault : I had some mess in the code. It works with my version of Glib/Python, but it seems they have changed the behavior of GLib.idle_add very slightly in the versions of Fedora, which made the error suddenly ... obvious.

**Comment by jflesch** [comment] 2016-11-12 19:44
I'm going to close this ticket.
Managing 2 bug trackers (one for Paperwork-gui and one for Paperwork-backend) is obviously going to be painful for me, so I'm also going to close this bug tracker.

You can try this fix if you like (in the branch 'stable' ; beware, default is 'unstable'). If you still have problems with this fix, please reopen a ticket, but on Paperwork bugtracker.

Thank you for taking the time of reporting this bug :)

**Closed by jflesch** 2016-11-12 19:44 UTC
Labels: bug
